<a href="https://colab.research.google.com/github/Rahulcva/-KNN-and-PCA-model-for-breast-cancer-classification/blob/main/pca.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [145]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/breast-cancer-wisconsin-data")

print("Path to dataset files:", path)

Path to dataset files: /root/.cache/kagglehub/datasets/uciml/breast-cancer-wisconsin-data/versions/2


In [146]:
import pandas as pd
import numpy as np



In [147]:
# Assuming the dataset is in CSV format
data_path = path + '/data.csv'  # Replace with the correct path and filename
df = pd.read_csv(data_path)

In [148]:
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [149]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [150]:
#using df we see full dataset and usinf df.head() we see top 5 row and using df.tail() we see last 5 row and using df.smaple() we see any random row of the dataset

In [151]:
df.sample()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
90  861648         B        14.62         24.02           94.57      662.7   

    smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
90          0.08974           0.08606         0.03102              0.02957   

    ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
90  ...          29.11            102.9       803.7            0.1115   

    compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
90             0.1766          0.09189               0.06946          0.2522   

    fractal_dimension_worst  Unnamed: 32  
90                  0.07246          NaN  

[1 rows x 33 columns]

In [152]:
# Assuming the 'diagnosis' column has string values like 'M' and 'B'
df['diagnosis'] = df['diagnosis'].map({'M': 1, 'B': 0})



In [153]:
df.head()

id  diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302          1        17.99         10.38          122.80     1001.0   
1    842517          1        20.57         17.77          132.90     1326.0   
2  84300903          1        19.69         21.25          130.00     1203.0   
3  84348301          1        11.42         20.38           77.58      386.1   
4  84358402          1        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [154]:
#verify the missing value or Nan value
# Check for missing values in the dataset
missing_values = df.isnull().sum()

In [155]:
missing_values

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed: 32                569
dtype: int64

In [156]:
# Display columns with missing values
print(missing_values[missing_values > 0])

Unnamed: 32    569
dtype: int64


In [157]:
# Remove rows with any NaN values
df_cleaned = df.dropna()

In [158]:
df_cleaned

Empty DataFrame
Columns: [id, diagnosis, radius_mean, texture_mean, perimeter_mean, area_mean, smoothness_mean, compactness_mean, concavity_mean, concave points_mean, symmetry_mean, fractal_dimension_mean, radius_se, texture_se, perimeter_se, area_se, smoothness_se, compactness_se, concavity_se, concave points_se, symmetry_se, fractal_dimension_se, radius_worst, texture_worst, perimeter_worst, area_worst, smoothness_worst, compactness_worst, concavity_worst, concave points_worst, symmetry_worst, fractal_dimension_worst, Unnamed: 32]
Index: []

[0 rows x 33 columns]

In [159]:
#df.dropna(inplace=True)

In [160]:
# Drop any unnecessary columns (e.g., 'id' or 'Unnamed' columns)
df = df.drop(columns=['id', 'Unnamed: 32'], errors='ignore')


In [161]:
df

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0            1        17.99         10.38          122.80     1001.0   
1            1        20.57         17.77          132.90     1326.0   
2            1        19.69         21.25          130.00     1203.0   
3            1        11.42         20.38           77.58      386.1   
4            1        20.29         14.34          135.10     1297.0   
..         ...          ...           ...             ...        ...   
564          1        21.56         22.39          142.00     1479.0   
565          1        20.13         28.25          131.20     1261.0   
566          1        16.60         28.08          108.30      858.1   
567          1        20.60         29.33          140.10     1265.0   
568          0         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    .

In [162]:
x_train

array([[ 1.77441228,  2.35932161,  1.91226601, ...,  2.25330862,
         2.03215   ,  2.2008957 ],
       [-0.1322665 , -1.38923972, -0.19179709, ..., -0.8955658 ,
        -0.13570987, -0.90420962],
       [ 0.31439324,  0.82581925,  0.29904315, ...,  0.46725269,
        -0.59363596, -0.88537737],
       ...,
       [-0.53146865, -1.62264951, -0.56053374, ..., -0.15041231,
         0.35651781, -0.46220569],
       [-0.10993352, -0.46960512, -0.17643306, ..., -1.0017555 ,
        -0.92293113, -0.68930044],
       [ 1.81070339,  2.77712515,  1.73436674, ...,  0.74565834,
        -0.05853131, -0.11547077]])

In [163]:
df.tail()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
564          1        21.56         22.39          142.00     1479.0   
565          1        20.13         28.25          131.20     1261.0   
566          1        16.60         28.08          108.30      858.1   
567          1        20.60         29.33          140.10     1265.0   
568          0         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
564                0.2216          0.2060                  0.07115  
565                0.1628          0.2572                  0.06637  
566                0.1418          0.2218                  0.07820  
567                0.2650          0.4087                  0.12400  
568                0.0000          0.2871                  0.07039  

[5 rows x 31 columns]

In [164]:
df.sample()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
142          0        11.43         17.31           73.66      398.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
142           0.1092           0.09486         0.02031              0.01861   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
142         0.1645  ...         12.78          26.76            82.66   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
142       503.0            0.1413             0.1792          0.07708   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
142               0.06402          0.2584                  0.08096  

[1 rows x 31 columns]

In [165]:
df.shape

(569, 31)

In [166]:
#in this dataset have 33 column and 569 row

In [167]:
x=df.iloc[:,1:] #we skip 1st column but we are taking all row

In [168]:
y=df.iloc[:,0] #here we are taking all row but not taking any column

In [169]:
x

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     concavity_worst  concave points_worst  symmetry_worst  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [170]:
y

0      1
1      1
2      1
3      1
4      1
      ..
564    1
565    1
566    1
567    1
568    0
Name: diagnosis, Length: 569, dtype: int64

In [171]:
from sklearn.model_selection import train_test_split


In [172]:
#without pca
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [173]:
x_test

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
172       15.460         11.89          102.50      736.9          0.12570   
553        9.333         21.94           59.01      264.0          0.09240   
374       13.690         16.07           87.84      579.1          0.08302   
370       16.350         23.29          109.00      840.4          0.09742   
419       11.160         21.41           70.95      380.3          0.10180   
..           ...           ...             ...        ...              ...   
188       11.810         17.39           75.27      428.9          0.10070   
429       12.720         17.67           80.98      501.3          0.07896   
399       11.800         17.26           75.26      431.9          0.09087   
323       20.340         21.51          135.90     1264.0          0.11700   
262       17.290         22.13          114.40      947.8          0.08999   

     compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
172           0.15550        0.203200              0.10970         0.1966   
553           0.05605        0.039960              0.01282         0.1692   
374           0.06374        0.025560              0.02031         0.1872   
370           0.14970        0.181100              0.08773         0.2175   
419           0.05978        0.008955              0.01076         0.1615   
..                ...             ...                  ...            ...   
188           0.05562        0.023530              0.01553         0.1718   
429           0.04522        0.014020              0.01835         0.1459   
399           0.06232        0.028530              0.01638         0.1847   
323           0.18750        0.256500              0.15040         0.2569   
262           0.12730        0.096970              0.07507         0.2108   

     fractal_dimension_mean  ...  radius_worst  texture_worst  \
172                 0.07069  ...        18.790          17.04   
553                 0.06576  ...         9.845          25.05   
374                 0.05669  ...        14.840          20.21   
370                 0.06218  ...        19.380          31.03   
419                 0.06144  ...        12.360          28.92   
..                      ...  ...           ...            ...   
188                 0.05780  ...        12.570          26.48   
429                 0.05544  ...        13.820          20.96   
399                 0.06019  ...        13.450          24.49   
323                 0.06670  ...        25.300          31.86   
262                 0.05464  ...        20.390          27.24   

     perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
172           125.00      1102.0            0.1531            0.35830   
553            62.86       295.8            0.1103            0.08298   
374            99.16       670.6            0.1105            0.20960   
370           129.30      1165.0            0.1415            0.46650   
419            79.26       458.0            0.1282            0.11080   
..               ...         ...               ...                ...   
188            79.57       489.5            0.1356            0.10000   
429            88.87       586.8            0.1068            0.09605   
399            86.00       562.0            0.1244            0.17260   
323           171.10      1938.0            0.1592            0.44920   
262           137.90      1295.0            0.1134            0.28670   

     concavity_worst  concave points_worst  symmetry_worst  \
172          0.58300               0.18270          0.3216   
553          0.07993               0.02564          0.2435   
374          0.13460               0.06987          0.3323   
370          0.70870               0.22480          0.4824   
419          0.03582               0.04306          0.2976   
..               ...                   ...             ...   
188          0.08803               0.04306         

In [174]:
y_train

567    1
295    0
91     1
1      1
94     1
      ..
369    1
320    0
527    0
125    0
265    1
Name: diagnosis, Length: 455, dtype: int64

In [175]:
y_test

172    1
553    0
374    0
370    1
419    0
      ..
188    0
429    0
399    0
323    1
262    1
Name: diagnosis, Length: 114, dtype: int64

In [176]:
from sklearn.neighbors import KNeighborsClassifier

In [177]:
knn=KNeighborsClassifier()

In [178]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [179]:
y_pred=knn.predict(x_test)

In [180]:
y_pred

array([1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1])

In [181]:
from sklearn.metrics import accuracy_score

In [182]:
accuracy_score(y_test,y_pred)

0.9210526315789473

In [183]:
#now we are using a pca

In [184]:
from sklearn.preprocessing import StandardScaler

In [185]:
scaler=StandardScaler()

In [186]:
x_train=scaler.fit_transform(x_train) # Calculates mean and std dev from X_train and # Transform the training data (mean center and scale)

In [187]:
x_test=scaler.transform(x_test)
# Transform the test data using the same scaling parameters from X_train

In [188]:
from sklearn.decomposition import PCA
pca=PCA()

In [189]:
pca=PCA(n_components=None) # here we say how many principal component u want  if u give None so all column it take if u set specifially so u can do that

In [190]:
pca.fit(x_train)

PCA()

In [191]:
#for finding eigen vector
pca.explained_variance_

array([1.34982731e+01, 5.40298299e+00, 2.98093453e+00, 2.00137687e+00,
       1.64862003e+00, 1.19628621e+00, 7.25141065e-01, 4.79577357e-01,
       4.28675796e-01, 3.48524683e-01, 2.90678710e-01, 2.39608997e-01,
       1.70321476e-01, 1.53496639e-01, 9.84601051e-02, 8.55631792e-02,
       6.19683054e-02, 5.42667336e-02, 4.80909682e-02, 2.98935836e-02,
       2.80732721e-02, 2.76971699e-02, 2.25537875e-02, 1.69385631e-02,
       1.00828858e-02, 8.16813561e-03, 7.21955503e-03, 1.75081691e-03,
       7.37960199e-04, 1.15784219e-04])

In [192]:
#for finding eigen value
pca.components_

array([[ 2.22154625e-01,  1.10271173e-01,  2.30375894e-01,
         2.23575774e-01,  1.32187968e-01,  2.37893533e-01,
         2.58838999e-01,  2.59399812e-01,  1.25416915e-01,
         5.34569085e-02,  2.03053541e-01,  1.78708705e-02,
         2.09978740e-01,  2.01201401e-01,  1.02077073e-02,
         1.75304532e-01,  1.80632930e-01,  1.82071784e-01,
         3.14059697e-02,  1.03264362e-01,  2.30577957e-01,
         1.05689321e-01,  2.39331916e-01,  2.27722809e-01,
         1.16211355e-01,  2.10831976e-01,  2.29052466e-01,
         2.48815439e-01,  1.09398475e-01,  1.27788575e-01],
       [-2.29174073e-01, -5.71335379e-02, -2.09691151e-01,
        -2.26505881e-01,  2.06338407e-01,  1.63804031e-01,
         4.77114810e-02, -2.66511840e-02,  1.93571458e-01,
         3.80996934e-01, -9.98216325e-02,  9.32570615e-02,
        -8.05710338e-02, -1.43861015e-01,  2.09770896e-01,
         2.32852513e-01,  1.74623209e-01,  1.16116961e-01,
         1.78197096e-01,  2.83209378e-01, -2.13490257e-

In [193]:
#start we n_component so we know how many n component is important so we for this we apply cummulative sum
np.cumsum(pca.explained_variance_ratio_)

array([0.44895355, 0.62865716, 0.72780326, 0.79436921, 0.84920243,
       0.888991  , 0.91310924, 0.92906002, 0.94331781, 0.95490976,
       0.96457776, 0.97254717, 0.97821208, 0.98331739, 0.98659218,
       0.98943801, 0.99149908, 0.993304  , 0.99490351, 0.99589777,
       0.99683149, 0.9977527 , 0.99850284, 0.99906622, 0.99940158,
       0.99967325, 0.99991337, 0.9999716 , 0.99999615, 1.        ])

In [194]:
pca1=PCA(n_components=10) # here we say how many principal component u want  if u give None so all column it take if u set specifially so u can do that

In [195]:
pca1.fit(x_train)

PCA(n_components=10)

In [196]:
pca1.explained_variance_

array([13.49827314,  5.40298299,  2.98093453,  2.00137687,  1.64862003,
        1.19628621,  0.72514106,  0.47957736,  0.4286758 ,  0.34852468])

In [197]:
pca1.components_

array([[ 2.22154625e-01,  1.10271173e-01,  2.30375894e-01,
         2.23575774e-01,  1.32187968e-01,  2.37893533e-01,
         2.58838999e-01,  2.59399812e-01,  1.25416915e-01,
         5.34569085e-02,  2.03053541e-01,  1.78708705e-02,
         2.09978740e-01,  2.01201401e-01,  1.02077073e-02,
         1.75304532e-01,  1.80632930e-01,  1.82071784e-01,
         3.14059697e-02,  1.03264362e-01,  2.30577957e-01,
         1.05689321e-01,  2.39331916e-01,  2.27722809e-01,
         1.16211355e-01,  2.10831976e-01,  2.29052466e-01,
         2.48815439e-01,  1.09398475e-01,  1.27788575e-01],
       [-2.29174073e-01, -5.71335379e-02, -2.09691151e-01,
        -2.26505881e-01,  2.06338407e-01,  1.63804031e-01,
         4.77114810e-02, -2.66511840e-02,  1.93571458e-01,
         3.80996934e-01, -9.98216325e-02,  9.32570615e-02,
        -8.05710338e-02, -1.43861015e-01,  2.09770896e-01,
         2.32852513e-01,  1.74623209e-01,  1.16116961e-01,
         1.78197096e-01,  2.83209378e-01, -2.13490257e-

In [198]:
#take 90% of the variance min n_components

In [199]:
x_train1=pca1.fit_transform(x_train)

In [200]:
x_test1=pca1.transform(x_test)

In [201]:
x_train1.shape

(455, 10)

In [202]:
x_train.shape

(455, 30)

In [203]:
knn=KNeighborsClassifier()

In [204]:
knn.fit(x_train1,y_train)

KNeighborsClassifier()

In [205]:
y_pred1=knn.predict(x_test1)

In [206]:
accuracy_score(y_test,y_pred1)

0.9824561403508771